spring.application.name=Appluis

#Conexion MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/dbClientes_in5av?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=luis-2025576
//server.port=8003

#JPA / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
